## Requerimientos para el Primer Avance del Proyecto de Programación para Análisis de Datos en Python
### Aissa Berenice Gonzalez Fosado 752224

    1. Definición del Problema

Mi Dataset es de causas de muerte por pais y año Me gustaria primero cuantificar los datos que ya tiene para despues corelacionarla con algun otro dataset similar, como factores económicos, calidad de sistema de salud, y de servicios basicos, etc. Creo que es importante conocer las relaciones entre el contexto social y la salud de las personas, me gustaría saber más al respecto

    2. Recolección y Preparación de Datos

La fuente de donde obtume mis datos fue https://ghdx.healthdata.org/ que encontre en https://ourworldindata.org/ que son datasets publicos, personalice los datos mas necesarios para mi proyecto.
Mi primer paso sera revisar si hay datos faltantes y los transformare para poder visualizarlos, abajo hare un test para revisar si existen datos faltantes y poder visualizar el dataset


    3. Análisis Exploratorio de Datos (EDA)
Comence a revisar mis datos y com ejemplo de estadistica descriptiva encontre las medidas de tendencia central para uno de los features, pero para este paso, aun estoy intentando hacerlo con una funcion para no tener un codigo muy extenso y que un for pueda cuantificar los datos de cada feature como lo hice en este avance.
    
    4. Metodología
Las herramientas y librerías de Python que he usado hasta ahora son Pandas, Numpy y Matplotlyb, siento que sera muy util Seaborn pero aun no estoy tan familiarizada con ella. Sigue en proceso mi plan de analisis.


    7. Plan para los Siguientes Avances
Objetivos a corto plazo: Mis proximos pasos son hacer funciones para mi EDA de todos mis datos actuales, y asi poder tener insights de con lo que ya cuento, con esto espero poder escoger otros datos a los cuales coorrelacionarlos 
Desafíos identificados: Mi principal obstaculo es que no conozco el objetivo de mi analisis aun, pero espero encontrarlo en cuanto cuantifique mis datos de manera mas simple.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/raw/annual-number-of-deaths-by-cause.csv")
df
# Los datos Nulos en mi Dataframe significa que hay 0 ocurrencias, no que no hay datos

,Entity,Code,Year,Deaths - Meningitis - Sex: Both - Age: All Ages (Number),Deaths - Alzheimer's disease and other dementias - Sex: Both - Age: All Ages (Number),Deaths - Parkinson's disease - Sex: Both - Age: All Ages (Number),Deaths - Nutritional deficiencies - Sex: Both - Age: All Ages (Number),Deaths - Malaria - Sex: Both - Age: All Ages (Number),Deaths - Drowning - Sex: Both - Age: All Ages (Number),Deaths - Interpersonal violence - Sex: Both - Age: All Ages (Number),...,Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Poisonings - Sex: Both - Age: All Ages (Number),Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Deaths - Road injuries - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number),Deaths - Measles - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,3709,338,2054,4154,5945,2673,5005,323,2985,10037
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,3724,351,2119,4472,6050,2728,5120,332,3092,10021
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,3776,386,2404,5106,6223,2830,5335,360,3325,9807
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,3862,425,2797,5681,6445,2943,5568,396,3601,10228
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,3932,451,3038,6001,6664,3027,5739,420,3816,12144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,1439,754,215,3019,2518,770,1302,...,2108,381,2990,2373,2751,1956,4202,632,146,720
6836,Zimbabwe,ZWE,2016,1457,767,219,3056,2050,801,1342,...,2160,393,3027,2436,2788,1962,4264,648,146,432
6837,Zimbabwe,ZWE,2017,1460,781,223,2990,2116,818,1363,...,2196,398,2962,2473,2818,2007,4342,654,144,307
6838,Zimbabwe,ZWE,2018,1450,795,227,2918,2088,825,1396,...,2240,400,2890,2509,2849,2030,4377,657,139,402
6839,Zimbabwe,ZWE,2019,1450,812,232,2884,2068,827,1434,...,2292,405,2855,2554,2891,2065,4437,662,136,413

In [2]:
#Estadisticas Descriptivas de uno de los features

mean1 = df["Deaths - Meningitis - Sex: Both - Age: All Ages (Number)"].mean()
print(f'The Average for Meningitis Deaths is of  {mean1}')

median1 = df["Deaths - Meningitis - Sex: Both - Age: All Ages (Number)"].median()
print(f'The Median for Meningitis Deaths is of  {median1}')

mode1 = df["Deaths - Meningitis - Sex: Both - Age: All Ages (Number)"].mode()
print(f'The Median for Meningitis Deaths is of  {mode1}')

The Average for Meningitis Deaths is of  8213.149561403508
The Median for Meningitis Deaths is of  150.5
The Median for Meningitis Deaths is of  0    0
Name: Deaths - Meningitis - Sex: Both - Age: All Ages (Number), dtype: int64